### ISSUE TITLE
Orbbec Astra S Color stream

### ISSUE THREAD

**Issue by fisakhan** [roccopietrini/pyOniRecorder#1]
@rok thanks but I receive the following error at line "color_stream.set_mirroring_enabled(mirroring)"
AttributeError: 'NoneType' object has no attribute 'set_mirroring_enabled'.

dev.has_sensor(openni2.SENSOR_COLOR) returns "False" for my Orbbec Astra Stereo S USB 3.0 camera.
I successfully process depth and infrared stream with the the same camera.

Does it mean that my Astra Stereo S is not supporting COLOR STREAM?

**Comment by CharlesYuan02** [comment]
It's the same issue with my Astra 3D Sensor. Just delete the color parts in the code and it should be able to record.
